const http=require("node:http"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const { handleGeneralRoutes } = require("./challenges/scaffolding");
const PORT=Number(process.env.PORT||8090),ROOT=__dirname,DATA_DIR=path.join(ROOT,"data"),DB_FILE=process.env.SECKART_DATA_FILE||path.join(DATA_DIR,"runtime.json"),ROLES=["Customer","Seller","Admin"],sessions=new Map(),loginAttempts=new Map();
const rows=[
["Auralis One","Audio",24990,"🎧","Cloud White"],["Auralis Max","Audio",34990,"🎧","Silver"],["Sona Buds Pro","Audio",12990,"♫","Pearl"],["Sona Buds Mini","Audio",7990,"♪","Sky"],["Orbit Room","Smart Home",15990,"◉","White"],["Orbit Mini","Smart Home",8990,"●","Mist"],["Halo Desk Light","Smart Home",6990,"◒","Ivory"],["Halo Air Sensor","Smart Home",5990,"◎","Frost"],["Veyra Watch S2","Wearables",18990,"⌚","Natural"],["Veyra Watch Ultra","Wearables",29990,"⌚","Ocean"],["Veyra Band","Wearables",9990,"◌","Sage"],["Veyra Ring","Wearables",14990,"○","Silver"],["Northstar Air 13","Computing",89990,"▱","Silver"],["Northstar Pro 14","Computing",129990,"▰","Space Grey"],["Arc Keyboard","Computing",11990,"⌨","White"],["Arc Mouse","Computing",6990,"◈","White"],["Luma Display 27","Computing",74990,"▣","Silver"],["Luma Display Air","Computing",49990,"▢","Blue"],["Flow Charger Duo","Accessories",4990,"⌁","White"],["Flow Travel Hub","Accessories",6990,"⬡","Silver"],["QuietForm Stand","Accessories",8990,"△","Natural"],["Cloud Sleeve 14","Accessories",3990,"▭","Lavender"],["Frame Camera","Smart Home",11990,"◍","White"],["Frame Doorbell","Smart Home",9990,"▯","Graphite"],
["Nova Phone 16","Mobile",79990,"▤","Ultramarine"],["Nova Phone Air","Mobile",64990,"▤","Cloud"],["Nova Phone Mini","Mobile",49990,"▥","Mint"],["Nova Fold","Mobile",119990,"▥","Titanium"],["PixelCase Pro","Mobile",2990,"▯","Clear"],["GameCore X","Gaming",54990,"🎮","Obsidian"],["GameCore S","Gaming",34990,"🎮","Arctic"],["Pulse Controller","Gaming",7990,"♢","Violet"],["Vector Headset","Gaming",10990,"🎧","Black"],["Motion Dock","Gaming",12990,"⬢","Silver"],["Lens One","Cameras",68990,"◉","Graphite"],["Lens Pocket","Cameras",32990,"◉","Ivory"],["Vista Action 5","Cameras",27990,"▣","Black"],["Studio Light Mini","Cameras",8990,"☼","White"],["Focus Gimbal","Cameras",14990,"⌁","Grey"],["Aura Blender","Kitchen",11990,"♨","Cream"],["Aura Kettle","Kitchen",7990,"♨","Silver"],["ChefScale","Kitchen",4990,"▱","White"],["PureBrew One","Kitchen",18990,"◈","Stone"],["FreshBox Mini","Kitchen",9990,"□","Sage"],["Calm Air","Wellness",14990,"≈","White"],["Calm Sleep","Wellness",8990,"☾","Lavender"],["Move Mat","Wellness",5990,"▭","Sand"],["Breathe Mini","Wellness",3990,"◌","Sky"],["Therma Bottle","Wellness",4990,"♨","Graphite"]
];
const baseProducts=rows.map((r,i)=>({id:i+1,name:r[0],category:r[1],price:r[2],icon:r[3],finish:r[4],description:`${r[0]} combines thoughtful design with dependable everyday performance.`,stock:18+(i*11)%57,rating:(4.5+(i%5)*.1).toFixed(1),featured:i<8}));
const coupons=[{code:"WELCOME10",label:"Welcome offer",percent:10,hidden:false},{code:"SAVE20",label:"Seasonal offer",percent:20,hidden:false},{code:"VIP25",label:"Internal VIP offer",percent:25,hidden:true}];
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return`${salt}:${crypto.scryptSync(password,salt,64).toString("hex")}`};
function verifyPassword(password,stored){const [salt,hash]=stored.split(":");return crypto.timingSafeEqual(crypto.scryptSync(password,salt,64),Buffer.from(hash,"hex"))}
function seedUsers(){return[{id:"usr_customer",username:"customer",name:"Aarav Customer",email:"customer@seckart.local",role:"Customer",status:"active",password:hashPassword("Customer#Cart26")},{id:"usr_seller",username:"seller",name:"Samir Seller",email:"seller@seckart.local",role:"Seller",status:"active",password:hashPassword("Seller#Stock26")},{id:"usr_admin",username:"admin",name:"Anika Admin",email:"admin@seckart.local",role:"Admin",status:"active",password:hashPassword("Admin#Control26")}]}
function id(prefix){return`${prefix}_${crypto.randomBytes(8).toString("hex")}`}
function safeText(value,max=1000){return String(value||"").slice(0,max).replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&#39;",'\"':"&quot;"}[c]))}
function load(){fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});let d;try{d=JSON.parse(fs.readFileSync(DB_FILE,"utf8"))}catch{d={}}const seeds=seedUsers(),existing=Array.isArray(d.users)?d.users.filter(u=>ROLES.includes(u.role)):[];for(const s of seeds){const found=existing.find(u=>u.username===s.username);if(found){found.password=s.password;found.role=s.role;found.status="active"}else existing.push(s)}const reviews=Array.isArray(d.reviews)?d.reviews.map(r=>({...r,author:d.version>=6?String(r.author||"").slice(0,80):safeText(r.author,80),body:d.version>=6?String(r.body||"").slice(0,1000):safeText(r.body,1000),rating:Math.max(1,Math.min(5,Number(r.rating)||5))})):[];return{version:6,users:existing,orders:Array.isArray(d.orders)?d.orders:[],profiles:d.profiles||{},reviews,wishlists:d.wishlists||{},inventory:d.inventory||{},customProducts:d.customProducts||[],settings:{storeName:d.settings?.storeName||"SecKart",maintenanceMode:Boolean(d.settings?.maintenanceMode),allowCustomerSignup:d.settings?.allowCustomerSignup!==false},audit:Array.isArray(d.audit)?d.audit:[],resetTokens:{},refundEvents:d.refundEvents||[]}}
let db=load();function persist(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}persist();function publicUser(u){return{id:u.id,username:u.username,name:u.name,email:u.email,role:u.role,status:u.status}}
function products(){return[...baseProducts,...db.customProducts].map(base=>({...base,...(db.inventory[base.id]||{})}))}
function cookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").filter(Boolean).map(v=>{const i=v.indexOf("=");return[decodeURIComponent(v.slice(0,i).trim()),decodeURIComponent(v.slice(i+1))]}))}
function currentUser(req){const token=cookies(req).sk_session,s=token&&sessions.get(token);if(!s||s.expiresAt<Date.now()){if(token)sessions.delete(token);return null}return db.users.find(u=>u.id===s.userId&&u.status==="active")||null}
const securityHeaders={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Cross-Origin-Resource-Policy":"same-origin"};
function send(res,status,data,headers={}){res.writeHead(status,{...securityHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let raw="";req.on("data",c=>{raw+=c;if(raw.length>1e6)reject(new Error("Body too large"))});req.on("end",()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error("Invalid JSON"))}});req.on("error",reject)})}
function requireRole(req,res,allowed){const u=currentUser(req);if(!u){send(res,401,{error:"Authentication required"});return null}if(!allowed.includes(u.role)){send(res,403,{error:`${u.role} cannot access this resource`});return null}return u}
function audit(actor,event,target){db.audit.unshift({id:id("evt"),actorId:actor?.id||"anonymous",event,target,createdAt:new Date().toISOString()});db.audit=db.audit.slice(0,300)}
const cookie=(token,maxAge=28800)=>`sk_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}; Priority=High`;
function lineItems(items){return(Array.isArray(items)?items:[]).map(x=>{const p=products().find(p=>p.id===Number(x.productId)),quantity=Math.max(1,Math.min(5,Number(x.quantity)||1));return p?{productId:p.id,name:p.name,icon:p.icon,quantity,unitPrice:p.price,lineTotal:p.price*quantity}:null}).filter(Boolean)}
function priceOrder(items,codes=[]){const lines=lineItems(items),subtotal=lines.reduce((n,l)=>n+l.lineTotal,0),valid=[...new Set(codes.map(c=>String(c).toUpperCase()))].map(c=>coupons.find(x=>x.code===c&&!x.hidden)).filter(Boolean).slice(0,1),discount=valid.reduce((n,c)=>n+Math.round(subtotal*c.percent/100),0),tax=Math.round((subtotal-discount)*.18);return{lines,subtotal,coupons:valid.map(c=>c.code),discount,tax,shipping:0,total:Math.max(0,subtotal-discount+tax)}}
async function api(req,res,url){
 const d=["POST","PATCH","PUT","DELETE"].includes(req.method)?await readBody(req).catch(()=>({})):{};
 if(await handleGeneralRoutes(req,res,url,db,sessions,currentUser(req),d))return;
 if(req.method==="GET"&&url.pathname==="/api/products")return send(res,200,{products:products()});
 if(req.method==="GET"&&url.pathname==="/api/system/health")return send(res,200,{status:"ok"});
 if(req.method==="GET"&&url.pathname==="/api/auth/me")return send(res,200,{user:currentUser(req)?publicUser(currentUser(req)):null});
 if(req.method==="POST"&&url.pathname==="/api/auth/login"){const key=String(d.identity||"").toLowerCase().trim(),attemptKey=`${req.socket.remoteAddress}:${key}`,now=Date.now(),attempt=loginAttempts.get(attemptKey)||{count:0,lockedUntil:0};if(attempt.lockedUntil>now)return send(res,429,{error:"Too many sign-in attempts. Try again later."},{"Retry-After":"900"});const u=db.users.find(x=>x.username.toLowerCase()===key||x.email.toLowerCase()===key);if(!u||!verifyPassword(String(d.password||""),u.password)||u.status!=="active"){attempt.count++;if(attempt.count>=5)attempt.lockedUntil=now+900000;loginAttempts.set(attemptKey,attempt);audit(null,"login_failed",key.slice(0,64));persist();return send(res,401,{error:"Invalid username or password"})}loginAttempts.delete(attemptKey);const remembered=d.rememberMe===true||d.rememberMe==="on",token=crypto.randomBytes(32).toString("hex"),maxAge=remembered?2592000:28800;sessions.set(token,{userId:u.id,expiresAt:now+maxAge*1000});audit(u,"login_success","session");persist();return send(res,200,{user:publicUser(u),remembered},{"Set-Cookie":cookie(token,maxAge)})}
 if(req.method==="POST"&&url.pathname==="/api/auth/signup"){const email=String(d.email||"").toLowerCase().trim(),username=String(d.username||"").toLowerCase().trim(),password=String(d.password||""),strong=password.length>=12&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password);if(!db.settings.allowCustomerSignup)return send(res,403,{error:"Customer registration is currently disabled"});if(!/^[a-z0-9._-]{3,24}$/.test(username)||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||!strong)return send(res,400,{error:"Use a valid username, email, and a 12+ character password with upper, lower, number, and symbol"});if(db.users.some(u=>u.username===username||u.email===email))return send(res,409,{error:"Username or email already exists"});const u={id:id("usr"),username,name:safeText(d.name||username,80),email,role:"Customer",status:"active",password:hashPassword(password)};db.users.push(u);audit(u,"account_created",u.id);persist();const token=crypto.randomBytes(32).toString("hex");sessions.set(token,{userId:u.id,expiresAt:Date.now()+28800000});return send(res,201,{user:publicUser(u)},{"Set-Cookie":cookie(token)})}
 if(req.method==="POST"&&url.pathname==="/api/auth/logout"){sessions.delete(cookies(req).sk_session);return send(res,200,{ok:true},{"Set-Cookie":cookie("",0)})}
 if(req.method==="POST"&&url.pathname==="/api/auth/reset"){const u=db.users.find(x=>x.email===String(d.email||"").toLowerCase()||x.username.toLowerCase()===String(d.email||"").toLowerCase());if(u){const token=crypto.randomBytes(32).toString("base64url");db.resetTokens[u.id]={tokenHash:crypto.createHash("sha256").update(token).digest("hex"),expiresAt:Date.now()+900000};audit(u,"password_reset_requested",u.id);persist()}return send(res,200,{message:"If that account exists, password reset instructions have been processed."})}
 if(req.method==="POST"&&url.pathname==="/api/auth/reset/confirm"){const key=String(d.email||d.username||d.identity||"").toLowerCase().trim(),newPassword=String(d.newPassword||d.password||""),strong=newPassword.length>=12&&/[a-z]/.test(newPassword)&&/[A-Z]/.test(newPassword)&&/\d/.test(newPassword)&&/[^A-Za-z0-9]/.test(newPassword);if(!strong)return send(res,400,{error:"Use a strong password (12+ chars with upper, lower, number, and symbol)"});const u=db.users.find(x=>x.email===key||x.username.toLowerCase()===key);if(!u)return send(res,404,{error:"Account not found"});u.password=hashPassword(newPassword);if(db.resetTokens[u.id])delete db.resetTokens[u.id];audit(u,"password_reset_completed",u.id);persist();return send(res,200,{message:"Password reset successfully. You can now sign in."})}
 if(req.method==="GET"&&url.pathname==="/api/customer/profile"){const u=requireRole(req,res,["Customer"]);if(!u)return;return send(res,200,{profile:{name:u.name,email:u.email,phone:"",addresses:[],...db.profiles[u.id]}})}
 if(req.method==="PATCH"&&url.pathname==="/api/customer/profile"){const u=requireRole(req,res,["Customer"]);if(!u)return;const phone=String(d.phone||"").replace(/[^\d+ -]/g,"").slice(0,24),addresses=Array.isArray(d.addresses)?d.addresses.slice(0,3).map(a=>({address:safeText(a.address,160),city:safeText(a.city,80),postalCode:safeText(a.postalCode,20)})):db.profiles[u.id]?.addresses||[];u.name=safeText(d.name||u.name,80);db.profiles[u.id]={...db.profiles[u.id],phone,addresses};audit(u,"profile_updated",u.id);persist();return send(res,200,{profile:{name:u.name,email:u.email,role:u.role,...db.profiles[u.id]}})}
 if(req.method==="GET"&&url.pathname==="/api/customer/wishlist"){const u=requireRole(req,res,["Customer"]);if(!u)return;return send(res,200,{productIds:db.wishlists[u.id]||[]})}
 if(req.method==="POST"&&url.pathname==="/api/customer/wishlist"){const u=requireRole(req,res,["Customer"]);if(!u)return;const pid=Number(d.productId);db.wishlists[u.id]=[...new Set([...(db.wishlists[u.id]||[]),pid])].filter(id=>products().some(p=>p.id===id));persist();return send(res,200,{productIds:db.wishlists[u.id]})}
 if(req.method==="DELETE"&&url.pathname.startsWith("/api/customer/wishlist/")){const u=requireRole(req,res,["Customer"]);if(!u)return;const pid=Number(url.pathname.split("/").pop());db.wishlists[u.id]=(db.wishlists[u.id]||[]).filter(x=>x!==pid);persist();return send(res,200,{productIds:db.wishlists[u.id]})}
 if(req.method==="POST"&&url.pathname==="/api/reviews"){const u=requireRole(req,res,ROLES);if(!u)return;const productId=Number(d.productId),rating=Math.max(1,Math.min(5,Number(d.rating)||5));if(!products().some(p=>p.id===productId))return send(res,400,{error:"Valid product required"});const review={id:id("rev"),productId,author:safeText(u.name,80),rating,body:safeText(d.body,1000),createdAt:new Date().toISOString()};db.reviews.unshift(review);audit(u,"review_created",review.id);persist();return send(res,201,{review})}
 if(req.method==="GET"&&url.pathname==="/api/reviews"){const productId=Number(url.searchParams.get("productId"));return send(res,200,{reviews:db.reviews.filter(r=>!productId||r.productId===productId)})}
 /* Coupon lookup exposes only active public offers; checkout applies at most one. */
 if(req.method==="GET"&&url.pathname==="/api/coupons/search"){const q=String(url.searchParams.get("q")||"").toUpperCase();return send(res,200,{coupons:coupons.filter(c=>!c.hidden&&c.code.includes(q)).map(({hidden,...c})=>c)})}
 if(req.method==="POST"&&url.pathname==="/api/checkout/preview"){const u=requireRole(req,res,ROLES);if(!u)return;const priced=priceOrder(d.items,d.couponCodes);if(!priced.lines.length)return send(res,400,{error:"Your bag is empty"});return send(res,200,{preview:priced})}
 if(req.method==="POST"&&url.pathname==="/api/checkout/intent"){const u=requireRole(req,res,ROLES);if(!u)return;const priced=priceOrder(d.items,d.couponCodes);if(!priced.lines.length)return send(res,400,{error:"Your bag is empty"});const intent={id:id("pi"),userId:u.id,...priced,status:"requires_payment_method",expiresAt:Date.now()+900000};sessions.set(intent.id,intent);return send(res,201,{intent:{...intent,userId:undefined}})}
 if(req.method==="POST"&&url.pathname==="/api/checkout/confirm"){const u=requireRole(req,res,ROLES);if(!u)return;const intent=sessions.get(String(d.intentId||""));if(!intent||intent.userId!==u.id)return send(res,400,{error:"Payment session expired"});const card=String(d.cardNumber||"").replace(/\D/g,"");if(card==="4000000000000002"){audit(u,"payment_declined",intent.id);persist();return send(res,402,{error:"The test bank declined this payment"})}if(card!=="4242424242424242"){audit(u,"payment_validation_failed",intent.id);persist();return send(res,400,{error:"Use approved test card 4242 4242 4242 4242"})}const order={id:`SK-${3001+db.orders.length}`,userId:u.id,customerName:u.name,lines:intent.lines,subtotal:intent.subtotal,discount:intent.discount,coupons:intent.coupons,tax:intent.tax,total:intent.total,status:"confirmed",refundCount:0,payment:{status:"authorized",last4:"4242"},shipping:{name:safeText(d.name,80),address:safeText(d.address,160),city:safeText(d.city,80),postalCode:safeText(d.postalCode,20)},createdAt:new Date().toISOString()};db.orders.unshift(order);sessions.delete(intent.id);audit(u,"order_confirmed",order.id);persist();return send(res,201,{order})}
 if(req.method==="GET"&&url.pathname==="/api/orders"){const u=requireRole(req,res,ROLES);if(!u)return;return send(res,200,{orders:u.role==="Customer"?db.orders.filter(o=>o.userId===u.id):db.orders})}
 const orderObject=url.pathname.match(/^\/api\/orders\/([^/]+)$/);if(req.method==="GET"&&orderObject){const u=requireRole(req,res,ROLES);if(!u)return;const order=db.orders.find(o=>o.id===orderObject[1]&&(u.role!=="Customer"||o.userId===u.id));return order?send(res,200,{order}):send(res,404,{error:"Order not found"})}
 if(req.method==="GET"&&url.pathname==="/api/seller/overview"){const u=requireRole(req,res,["Seller","Admin"]);if(!u)return;return send(res,200,{metrics:{products:products().length,lowStock:products().filter(p=>p.stock<20).length,orders:db.orders.length,revenue:db.orders.reduce((n,o)=>n+o.total,0)},products:products(),orders:db.orders.slice(0,20)})}
 if(req.method==="POST"&&url.pathname==="/api/seller/products"){const u=requireRole(req,res,["Seller","Admin"]);if(!u)return;const p={id:Math.max(0,...products().map(p=>p.id))+1,name:String(d.name||"New product"),category:String(d.category||"Accessories"),price:Math.max(100,Number(d.price)||100),stock:Math.max(0,Number(d.stock)||0),icon:String(d.icon||"□"),finish:String(d.finish||"Standard"),description:String(d.description||"Seller-created catalogue product."),rating:"4.5",featured:false};db.customProducts.push(p);audit(u,"product_created",String(p.id));persist();return send(res,201,{product:p})}
 const inv=url.pathname.match(/^\/api\/seller\/inventory\/(\d+)$/);if(req.method==="PATCH"&&inv){const u=requireRole(req,res,["Seller","Admin"]);if(!u)return;const pid=Number(inv[1]),p=products().find(x=>x.id===pid);if(!p)return send(res,404,{error:"Product not found"});db.inventory[pid]={stock:Math.max(0,Number(d.stock)),price:Math.max(100,Number(d.price))};audit(u,"inventory_updated",String(pid));persist();return send(res,200,{product:{...p,...db.inventory[pid]}})}
 if(req.method==="POST"&&url.pathname==="/api/seller/inventory/bulk"){const u=requireRole(req,res,["Seller","Admin"]);if(!u)return;const rows=Array.isArray(d.rows)?d.rows:[];for(const row of rows){if(products().some(p=>p.id===Number(row.id)))db.inventory[Number(row.id)]={stock:Math.max(0,Number(row.stock)||0),price:Math.max(100,Number(row.price)||100)}}persist();return send(res,200,{updated:rows.length})}
 if(req.method==="POST"&&url.pathname==="/api/customer/product-image/process"){const u=requireRole(req,res,["Customer"]);if(!u)return;const fileName=String(d.fileName||""),fileSize=Number(d.fileSize||0);if(!/^[a-zA-Z0-9._-]+\.(png|jpe?g|webp)$/i.test(fileName)||fileSize<0||fileSize>5_000_000)return send(res,400,{error:"Use a PNG, JPEG, or WebP image up to 5 MB"});audit(u,"review_image_validated",fileName);persist();return send(res,201,{file:fileName,processed:true})}
 if(req.method==="POST"&&url.pathname==="/api/customer/product-import"){const u=requireRole(req,res,["Customer"]);if(!u)return;const manifest=d.manifest;if(!manifest||typeof manifest!=="object"||!Array.isArray(manifest.productIds)||manifest.productIds.length>100)return send(res,400,{error:"Invalid product import format"});const productIds=[...new Set(manifest.productIds.map(Number))].filter(pid=>products().some(p=>p.id===pid));db.wishlists[u.id]=[...new Set([...(db.wishlists[u.id]||[]),...productIds])];audit(u,"saved_products_imported",String(productIds.length));persist();return send(res,201,{accepted:true,imported:productIds.length})}
 const refund=url.pathname.match(/^\/api\/seller\/orders\/([^/]+)\/refund$/);if(req.method==="POST"&&refund){const u=requireRole(req,res,["Seller","Admin"]);if(!u)return;const order=db.orders.find(o=>o.id===refund[1]);if(!order)return send(res,404,{error:"Order not found"});if(order.refundCount)return send(res,409,{error:"Order was already refunded"});order.refundCount=1;order.status="refunded";db.refundEvents.push({id:id("ref"),orderId:order.id,sequence:1,amount:order.total,createdAt:new Date().toISOString()});audit(u,"order_refunded",order.id);persist();return send(res,201,{refund:{orderId:order.id,sequence:1,amount:order.total}})}
 if(req.method==="GET"&&url.pathname==="/api/admin/overview"){const u=requireRole(req,res,["Admin"]);if(!u)return;return send(res,200,{users:db.users.map(publicUser),settings:db.settings,audit:db.audit.slice(0,50),metrics:{users:db.users.length,products:products().length,orders:db.orders.length,revenue:db.orders.reduce((n,o)=>n+o.total,0)}})}
 const adminUser=url.pathname.match(/^\/api\/admin\/users\/([^/]+)$/);if(req.method==="PATCH"&&adminUser){const u=requireRole(req,res,["Admin"]);if(!u)return;const target=db.users.find(x=>x.id===adminUser[1]);if(!target)return send(res,404,{error:"User not found"});if(ROLES.includes(d.role))target.role=d.role;if(["active","disabled"].includes(d.status))target.status=d.status;audit(u,d.role?"user_role_changed":"user_status_changed",target.id);persist();return send(res,200,{user:publicUser(target),roleChangeAlertCreated:Boolean(d.role)})}
 if(req.method==="PATCH"&&url.pathname==="/api/admin/settings"){const u=requireRole(req,res,["Admin"]);if(!u)return;db.settings={...db.settings,storeName:String(d.storeName||db.settings.storeName),maintenanceMode:Boolean(d.maintenanceMode),allowCustomerSignup:Boolean(d.allowCustomerSignup)};audit(u,"settings_updated","global");persist();return send(res,200,{settings:db.settings})}
 return send(res,404,{error:"API route not found"})
}
const staticMap={"/":"index.html","/index.html":"index.html","/styles.css":"styles.css","/app.js":"app.js"},mime={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".png":"image/png"};
function serve(res,url){let rel=staticMap[url.pathname];if(!rel&&url.pathname.startsWith("/assets/"))rel=url.pathname.slice(1);if(!rel)return send(res,404,{error:"Not found"});const target=path.resolve(ROOT,rel);if(!target.startsWith(ROOT)||!fs.existsSync(target))return send(res,404,{error:"Not found"});res.writeHead(200,{...securityHeaders,"Content-Security-Policy":"default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'","Content-Type":mime[path.extname(target)]||"application/octet-stream","Cache-Control":rel.startsWith("assets/")?"public,max-age=86400":"no-cache"});fs.createReadStream(target).pipe(res)}
function trustedBrowserRequest(req){if(["GET","HEAD","OPTIONS"].includes(req.method))return true;const origin=req.headers.origin;if(!origin)return true;return origin===`http://${req.headers.host}`||origin===`https://${req.headers.host}`}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);try{if(url.pathname.startsWith("/api/")&&!trustedBrowserRequest(req))return send(res,403,{error:"Cross-origin request blocked"});url.pathname.startsWith("/api/")?await api(req,res,url):serve(res,url)}catch(e){console.error(e);if(!res.headersSent)send(res,500,{error:"Unexpected server error"})}});if(require.main===module)server.listen(PORT,"127.0.0.1",()=>console.log(`SecKart running at http://127.0.0.1:${PORT}`));module.exports={server,baseProducts,ROLES};
