const test=require("node:test"),assert=require("node:assert/strict"),{spawn}=require("node:child_process"),path=require("node:path"),os=require("node:os"),fs=require("node:fs");
const BASE="http://127.0.0.1:8193",dataFile=path.join(os.tmpdir(),`seckart-security-${process.pid}.json`);let child;
async function wait(){for(let i=0;i<60;i++){try{if((await fetch(`${BASE}/api/products`)).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error("server did not start")}
async function req(url,{method="GET",body,cookie,headers={}}={}){const r=await fetch(BASE+url,{method,headers:{...(body?{"Content-Type":"application/json"}:{}),...(cookie?{Cookie:cookie}:{}),...headers},body:body?JSON.stringify(body):undefined}),data=await r.json().catch(()=>({}));return{status:r.status,data,setCookie:r.headers.get("set-cookie")||"",cookie:r.headers.get("set-cookie")?.split(";")[0]}}
const passwords={customer:"Customer#Cart26",seller:"Seller#Stock26",admin:"Admin#Control26"};
async function login(identity,rememberMe=false){const r=await req("/api/auth/login",{method:"POST",body:{identity,password:passwords[identity],rememberMe}});assert.equal(r.status,200);return r}
test.before(async()=>{child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:"8193",SECKART_DATA_FILE:dataFile},stdio:"ignore"});await wait()});test.after(()=>{child?.kill();try{fs.unlinkSync(dataFile)}catch{}});
test("catalogue and role boundaries remain operational",async()=>{assert.equal((await req("/api/products")).data.products.length,49);const c=await login("customer"),s=await login("seller"),a=await login("admin");assert.equal((await req("/api/admin/overview",{cookie:c.cookie})).status,403);assert.equal((await req("/api/seller/overview",{cookie:s.cookie})).status,200);assert.equal((await req("/api/admin/overview",{cookie:a.cookie})).status,200)});
test("profile mass assignment cannot escalate privileges",async()=>{const c=await login("customer"),x=await req("/api/customer/profile",{method:"PATCH",cookie:c.cookie,body:{name:"Aarav Customer",role:"Admin"}});assert.equal(x.data.profile.role,"Customer");assert.equal((await req("/api/admin/overview",{cookie:c.cookie})).status,403)});
test("debug route is absent and security headers are present",async()=>{const debug=await fetch(BASE+"/debug"),home=await fetch(BASE+"/");assert.equal(debug.status,404);assert.match(home.headers.get("content-security-policy"),/default-src 'self'/);assert.equal(home.headers.get("x-frame-options"),"DENY");assert.equal(home.headers.get("permissions-policy"),"camera=(), microphone=(), geolocation=()")});
test("reset and Remember-Me tokens are random and undisclosed",async()=>{const reset=await req("/api/auth/reset",{method:"POST",body:{email:"customer@seckart.local"}});assert.equal(reset.data.demoToken,undefined);assert.equal(reset.data.token,undefined);const first=await login("customer",true),second=await login("customer",true);assert.notEqual(first.cookie,second.cookie);assert.doesNotMatch(first.cookie,/remember-|usr_customer/);assert.match(first.setCookie,/HttpOnly/);assert.match(first.setCookie,/SameSite=Strict/)});
test("reviews are validated and encoded",async()=>{const c=await login("customer"),payload='<img src=x onerror=alert(1)>',x=await req("/api/reviews",{method:"POST",cookie:c.cookie,body:{productId:1,rating:9,body:payload}});assert.equal(x.status,201);assert.equal(x.data.review.rating,5);assert.doesNotMatch(x.data.review.body,/<img/);assert.match(x.data.review.body,/&lt;img/);assert.equal(x.data.renderedHtml,undefined)});
test("coupon exclusivity and server prices are enforced",async()=>{const c=await login("customer"),x=await req("/api/checkout/intent",{method:"POST",cookie:c.cookie,body:{items:[{productId:1,quantity:1,unitPrice:1}],couponCodes:["WELCOME10","SAVE20","WELCOME10"]}});assert.deepEqual(x.data.intent.coupons,["WELCOME10"]);assert.equal(x.data.intent.lines[0].unitPrice,24990);assert.equal(x.data.intent.subtotal,24990)});
test("declined payments create an audit event",async()=>{const c=await login("customer"),i=await req("/api/checkout/intent",{method:"POST",cookie:c.cookie,body:{items:[{productId:1,quantity:1}]}});assert.equal((await req("/api/checkout/confirm",{method:"POST",cookie:c.cookie,body:{intentId:i.data.intent.id,cardNumber:"4000000000000002"}})).status,402);const a=await login("admin"),o=await req("/api/admin/overview",{cookie:a.cookie});assert.equal(o.data.audit.some(e=>e.event==="payment_declined"),true)});
test("image and product imports reject unsafe input without verbose errors",async()=>{const c=await login("customer"),image=await req("/api/customer/product-image/process",{method:"POST",cookie:c.cookie,body:{fileName:"payload.exe",fileSize:1}});assert.equal(image.status,400);assert.equal(image.data.processor,undefined);const bad=await req("/api/customer/product-import",{method:"POST",cookie:c.cookie,body:{manifest:{name:"CRASH_IMPORT"}}});assert.equal(bad.status,400);assert.equal(bad.data.stack,undefined);const good=await req("/api/customer/product-import",{method:"POST",cookie:c.cookie,body:{manifest:{productIds:[1,2,999]}}});assert.equal(good.status,201);assert.equal(good.data.imported,2)});
test("cross-origin browser mutations are blocked",async()=>{const x=await req("/api/auth/reset",{method:"POST",headers:{Origin:"https://attacker.example"},body:{email:"customer@seckart.local"}});assert.equal(x.status,403)});
